task: korsts_small_v1
train_file: /dialog_electra/finetune/data/korsts/sts-train.tsv
test_file: /dialog_electra/finetune/data/korsts/sts-test.tsv
dev_file: /dialog_electra/finetune/data/korsts/sts-dev.tsv
config_dir: /dialog_electra/finetune/conf
data_dir: /dialog_electra/finetune/data
ckpt_dir: /dialog_electra/finetune/model
mecab: false
evaluate_test_during_training: true
eval_all_checkpoints: true
save_optimizer: false
do_lower_case: false
do_train: true
do_eval: true
max_seq_len: 128
num_train_epochs: 10
weight_decay: 0.0
gradient_accumulation_steps: 1
adam_epsilon: 1e-8
warmup_proportion: 0
max_steps: -1
max_grad_norm: 1.0
no_cuda: false
model_type: electra-small
model_name_or_path: /dialog_electra/finetune/dialog-wordpiece-koelectra-small-discriminator
seed: 42
train_batch_size: 32
eval_batch_size: 64
logging_steps: 100
save_steps: 100
learning_rate: 5e-5
